#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by ZSA Attackathon 2025 Instascope

set -e

echo "Building 16 contracts individually..."
echo ""

echo "Building AaveOracle (contract_AaveOracle_8105)"
FOUNDRY_PROFILE=contract_AaveOracle_8105 forge build || {
  echo "❌ Failed to build AaveOracle"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveOracle_8105 forge build"
}
echo "✅ Built AaveOracle"
echo ""

echo "Building ACLManager (contract_ACLManager_da13)"
FOUNDRY_PROFILE=contract_ACLManager_da13 forge build || {
  echo "❌ Failed to build ACLManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ACLManager_da13 forge build"
}
echo "✅ Built ACLManager"
echo ""

echo "Building EmissionManager (contract_EmissionManager_f09e)"
FOUNDRY_PROFILE=contract_EmissionManager_f09e forge build || {
  echo "❌ Failed to build EmissionManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EmissionManager_f09e forge build"
}
echo "✅ Built EmissionManager"
echo ""

echo "Building InitializableAdminUpgradeabilityProxy (contract_InitializableAdminUpgradeabilityProxy_4370)"
FOUNDRY_PROFILE=contract_InitializableAdminUpgradeabilityProxy_4370 forge build || {
  echo "❌ Failed to build InitializableAdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializableAdminUpgradeabilityProxy_4370 forge build"
}
echo "✅ Built InitializableAdminUpgradeabilityProxy"
echo ""

echo "Building InitializableImmutableAdminUpgradeabilityProxy (contract_InitializableImmutableAdminUpgradeabilityProxy_c13e)"
FOUNDRY_PROFILE=contract_InitializableImmutableAdminUpgradeabilityProxy_c13e forge build || {
  echo "❌ Failed to build InitializableImmutableAdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializableImmutableAdminUpgradeabilityProxy_c13e forge build"
}
echo "✅ Built InitializableImmutableAdminUpgradeabilityProxy"
echo ""

echo "Building PoolAddressesProvider (contract_PoolAddressesProvider_02c3)"
FOUNDRY_PROFILE=contract_PoolAddressesProvider_02c3 forge build || {
  echo "❌ Failed to build PoolAddressesProvider"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PoolAddressesProvider_02c3 forge build"
}
echo "✅ Built PoolAddressesProvider"
echo ""

echo "Building PoolAddressesProviderRegistry (contract_PoolAddressesProviderRegistry_03cf)"
FOUNDRY_PROFILE=contract_PoolAddressesProviderRegistry_03cf forge build || {
  echo "❌ Failed to build PoolAddressesProviderRegistry"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PoolAddressesProviderRegistry_03cf forge build"
}
echo "✅ Built PoolAddressesProviderRegistry"
echo ""

echo "Building InitializableImmutableAdminUpgradeabilityProxy (contract_InitializableImmutableAdminUpgradeabilityProxy_542d)"
FOUNDRY_PROFILE=contract_InitializableImmutableAdminUpgradeabilityProxy_542d forge build || {
  echo "❌ Failed to build InitializableImmutableAdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializableImmutableAdminUpgradeabilityProxy_542d forge build"
}
echo "✅ Built InitializableImmutableAdminUpgradeabilityProxy"
echo ""

echo "Building SavingsDaiOracle (contract_SavingsDaiOracle_b9e6)"
FOUNDRY_PROFILE=contract_SavingsDaiOracle_b9e6 forge build || {
  echo "❌ Failed to build SavingsDaiOracle"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SavingsDaiOracle_b9e6 forge build"
}
echo "✅ Built SavingsDaiOracle"
echo ""

echo "Building InitializableAdminUpgradeabilityProxy (contract_InitializableAdminUpgradeabilityProxy_b137)"
FOUNDRY_PROFILE=contract_InitializableAdminUpgradeabilityProxy_b137 forge build || {
  echo "❌ Failed to build InitializableAdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializableAdminUpgradeabilityProxy_b137 forge build"
}
echo "✅ Built InitializableAdminUpgradeabilityProxy"
echo ""

echo "Building CollectorController (contract_CollectorController_92ef)"
FOUNDRY_PROFILE=contract_CollectorController_92ef forge build || {
  echo "❌ Failed to build CollectorController"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CollectorController_92ef forge build"
}
echo "✅ Built CollectorController"
echo ""

echo "Building WrappedTokenGatewayV3 (contract_WrappedTokenGatewayV3_bd7d)"
FOUNDRY_PROFILE=contract_WrappedTokenGatewayV3_bd7d forge build || {
  echo "❌ Failed to build WrappedTokenGatewayV3"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WrappedTokenGatewayV3_bd7d forge build"
}
echo "✅ Built WrappedTokenGatewayV3"
echo ""

echo "Building RewardsController (contract_RewardsController_0ee5)"
FOUNDRY_PROFILE=contract_RewardsController_0ee5 forge build || {
  echo "❌ Failed to build RewardsController"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_RewardsController_0ee5 forge build"
}
echo "✅ Built RewardsController"
echo ""

echo "Building Pool (contract_Pool_5ae3)"
FOUNDRY_PROFILE=contract_Pool_5ae3 forge build || {
  echo "❌ Failed to build Pool"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Pool_5ae3 forge build"
}
echo "✅ Built Pool"
echo ""

echo "Building PoolConfigurator (contract_PoolConfigurator_f7b6)"
FOUNDRY_PROFILE=contract_PoolConfigurator_f7b6 forge build || {
  echo "❌ Failed to build PoolConfigurator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PoolConfigurator_f7b6 forge build"
}
echo "✅ Built PoolConfigurator"
echo ""

echo "Building Collector (contract_Collector_f1e5)"
FOUNDRY_PROFILE=contract_Collector_f1e5 forge build || {
  echo "❌ Failed to build Collector"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Collector_f1e5 forge build"
}
echo "✅ Built Collector"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
